### ISSUE TITLE
request rime.nvim-scm-1.rockspec in project root

### ISSUE THREAD

**Issue by chujDK** [Freed-Wu/rime.nvim#3]
After the release of Lazy.nvim 11.0, the luarocks is now supported. However, it requires 
> [luarocks](https://luarocks.org/) `*-scm-1.rockspec` [file](https://github.com/luarocks/luarocks/wiki/Rockspec-format)
> [lazy.nvim docs](https://lazy.folke.io/packages)

to automatic building

So could you add [this `rime.nvim-scm-1.rockspec`](https://luarocks.org/manifests/Freed-Wu/rime.nvim-scm-1.rockspec) file to the project root, so anyone using lazy.nvim (including me) can easily install this plugin. Many thanks.

By the way, really good plugin!🚀

**Comment by Freed-Wu** [comment]
You can download rockspec from here: https://luarocks.org/modules/Freed-Wu/rime.nvim  It is updated automatically by CI/CD.
I guess it should exist some method to execute some command (such as wget XXXX.rockspec) after download a plugin?

Thanks for your kind.
