### ISSUE TITLE
failed to call `require('rime.nvim').setup`: expected table, got nil

### ISSUE THREAD

**Issue by chujDK** [Freed-Wu/rime.nvim#4]
I called

```lua
require('rime.nvim').setup({
  traits = {
    user_data_dir = "/my/user/data/dir"  
  },
})
```

like the README

> require('rime.nvim').setup({
    -- ...
})

However, it failed with `expected table, got nil`. After investigated the `lua/rime/nvim/init.lua`

```lua
---setup
---@param conf table
function M:setup(conf)
    M = vim.tbl_deep_extend("keep", conf, M)
end

```

It seems the right way to call it is using `require('rime.nvim'):setup`. Maybe it is a typo.

**Comment by Freed-Wu** [comment]
Yes. It's a typo.
