### ISSUE TITLE
Question: How to setup with lazy.nvim?

### ISSUE THREAD

**Issue by imkerberos** [Freed-Wu/rime.nvim#5]
I use lazy.nvim, but I don't know how to set up this plugin with it.
Thank you for creating such a powerful plugin.

**Comment by Freed-Wu** [comment]
Looks related to #3?

You need to compile binary lua module.
In my setting, the code is builtin by xmake (luarocks-build-xmake). In fact, use gcc directly without 
any build system should be also OK. https://codeberg.org/smeikx/rime.nvim/src/branch/tidy provide some document about it.
